### ISSUE TITLE
Unable to Initialize tableau object

### ISSUE THREAD

**Issue by judexavier** [tableau/datadev-hackathon#2]
I am getting the below error when trying to initialize the tableau object in script.js as part of the glitch tutorial.

![image](https://user-images.githubusercontent.com/8533354/79116228-ec65ad00-7d55-11ea-9327-fc4bb91518a4.png)

**Comment by KeshiaRose** [comment]
Which browser are you using? Chrome 80 will not work, could you try with Chrome 79? You can download it here: https://tableau.github.io/extensions-api/docs/trex_debugging.html#download-the-chromium-browser

**Comment by judexavier** [comment]
Thank you @KeshiaRose , I was indeed using Chrome 80 for debugging and was facing the issue. I downloaded chromium for 2019.1 and proceeding with the project steps now.
